/* VivaOps demo data — Melbourne-flavored */
window.DATA = {
  user: { name: "Maya Chen", role: "Manager", initials: "MC" },
  org: "Viva Melbourne",

  kpis: [
    { label: "Active leads", value: 28, delta: "+3 this week", up: true },
    { label: "Pipeline value", value: "$642k", delta: "+$84k vs 30d", up: true },
    { label: "Events next 30d", value: 9, delta: "2 inside 7d", up: false },
    { label: "Overdue tasks", value: 4, delta: "−2 from yest.", up: true },
  ],

  pipeline: [
    { stage: "New",         count: 7,  value: 142000, color: "var(--st-slate)" },
    { stage: "Qualified",   count: 5,  value: 168000, color: "var(--st-blue)" },
    { stage: "Proposal",    count: 6,  value: 224500, color: "var(--st-violet)" },
    { stage: "Negotiation", count: 4,  value: 192000, color: "var(--st-amber)" },
    { stage: "Won",         count: 9,  value: 388000, color: "var(--st-green)" },
    { stage: "Lost",        count: 3,  value:  48000, color: "var(--st-red)"   },
    { stage: "On hold",     count: 2,  value:  32000, color: "var(--st-cyan)"  },
  ],

  leads: [
    { id: "L-1042", name: "Olivia Bennett", company: "Bennett Family",   type: "Wedding",  source: "Website",  value: 78000,  stage: "Qualified",   owner: "Maya",  next: "Site visit · Fri 10:00", updated: "2h" },
    { id: "L-1041", name: "Atlas Capital",  company: "Atlas Capital",    type: "Corporate", source: "Referral", value: 124000, stage: "Proposal",    owner: "Jules", next: "Send v2 quote",          updated: "5h" },
    { id: "L-1040", name: "Priya & Aarav",  company: "Sharma–Patel",     type: "Wedding",  source: "Instagram",value: 92000,  stage: "Negotiation", owner: "Maya",  next: "Confirm florals",        updated: "1d" },
    { id: "L-1039", name: "MCG Foundation", company: "MCG Foundation",   type: "Gala",     source: "Direct",   value: 158000, stage: "Proposal",    owner: "Ravi",  next: "Venue walk-through",     updated: "1d" },
    { id: "L-1038", name: "Lina Park",      company: "Park · Birthday",  type: "Private",  source: "Website",  value: 22000,  stage: "New",         owner: "Jules", next: "Discovery call",         updated: "2d" },
    { id: "L-1037", name: "Hartley Wedding",company: "Hartley Family",   type: "Wedding",  source: "Referral", value: 168000, stage: "Won",         owner: "Maya",  next: "RUN SHEET · Sat 14 Jun", updated: "3d" },
    { id: "L-1036", name: "Northbank Co.",  company: "Northbank Co.",    type: "Corporate", source: "LinkedIn",value: 64000,  stage: "Qualified",   owner: "Ravi",  next: "Send capability deck",   updated: "3d" },
    { id: "L-1035", name: "Doyle 50th",     company: "Doyle Private",    type: "Private",  source: "Website",  value: 18500,  stage: "On hold",     owner: "Jules", next: "Reach out 1 Jun",        updated: "5d" },
  ],

  recentEvents: [
    { name: "Hartley Wedding",        when: "Sat 14 Jun",  venue: "Brighton Beach Pavilion",   status: "On track",      health: "ok"   },
    { name: "Atlas Capital · EOFY",   when: "Thu 26 Jun",  venue: "Crown Pearl Room",           status: "Proposal sent", health: "warn" },
    { name: "Sharma–Patel Sangeet",   when: "Fri 11 Jul",  venue: "Royal Exhibition Building",  status: "Catering open", health: "warn" },
    { name: "MCG Foundation Gala",    when: "Sat 02 Aug",  venue: "MCG Olympic Room",           status: "Walk-through",  health: "ok"   },
    { name: "Park Birthday · 40th",   when: "Sun 17 Aug",  venue: "Half Acre Riverside",        status: "Deposit due",   health: "crit" },
  ],

  tasks: [
    { t: "Confirm Bouquet count w/ Bloom & Vine", who: "Maya",  due: "Tomorrow", priority: "High",   tag: "Hartley" },
    { t: "Send v2 quote — Atlas EOFY",            who: "Jules", due: "Today",    priority: "High",   tag: "Atlas" },
    { t: "Tasting feedback to Pearl Room",        who: "Maya",  due: "Wed",      priority: "Medium", tag: "Atlas" },
    { t: "Venue walk-through — MCG",              who: "Ravi",  due: "Fri",      priority: "Medium", tag: "MCG" },
    { t: "Final RSVPs — Hartley",                 who: "Maya",  due: "Mon",      priority: "Low",    tag: "Hartley" },
  ],

  event: {
    id: "EV-2104",
    code: "HRT-W-0614",
    title: "Hartley Wedding",
    couple: "Elliot & Sophie Hartley",
    date: "Saturday, 14 June 2026",
    countdownDays: 19,
    guests: 142,
    venue: "Brighton Beach Pavilion",
    address: "1 Esplanade, Brighton VIC 3186",
    coordinator: "Maya Chen",
    budget: 168000,
    spent: 124300,
    deposit: "Paid · 12 Mar",
    balance: "Due 7 Jun",
    stage: "Confirmed",
    tabs: [
      { id: "overview", name: "Overview" },
      { id: "tasks",    name: "Tasks",     count: 11 },
      { id: "comms",    name: "Comms",     count: 38 },
      { id: "quotes",   name: "Quotes",    count: 3 },
      { id: "files",    name: "Files",     count: 22 },
      { id: "wo",       name: "Work orders", count: 7 },
      { id: "run",      name: "Run sheet" },
      { id: "checklist",name: "Checklist", count: 24 },
    ],
    runsheet: [
      { t: "13:30", title: "Suppliers bump-in",     sub: "Pavilion side gate · keys w/ Maya", who: "All", state: "done" },
      { t: "14:00", title: "Floral install begins", sub: "Bloom & Vine · arbor + 14 tables",  who: "Bloom & Vine", state: "done" },
      { t: "14:30", title: "AV setup",              sub: "FOH desk by bar, lapel x2",          who: "Soundtrip", state: "doing" },
      { t: "15:15", title: "Ceremony rehearsal",    sub: "Officiant + wedding party",          who: "Officiant", state: "next" },
      { t: "15:45", title: "Guest arrival",         sub: "Welcome drinks on terrace",          who: "FOH", state: "next" },
      { t: "16:00", title: "Ceremony",              sub: "Beach lawn · 30 min",                who: "Couple", state: "next" },
      { t: "16:45", title: "Canapés + photos",      sub: "Golden hour on jetty",               who: "Photo · Mei", state: "next" },
      { t: "18:00", title: "Reception entry",       sub: "Pavilion main room",                 who: "MC · Theo", state: "next" },
      { t: "19:30", title: "Speeches",              sub: "Best man → MOH → father-of-bride",   who: "MC · Theo", state: "next" },
      { t: "21:15", title: "Cake cut & first dance",sub: "Note: Aunt Vivian must be present",  who: "Couple", state: "next" },
      { t: "23:30", title: "Carriages",             sub: "Bus to Hilton South Wharf",          who: "Coach Co.", state: "next" },
    ],
    suppliers: [
      { name: "Bloom & Vine",   role: "Florals",     status: "Confirmed", value: 18500 },
      { name: "Pearl Catering", role: "Catering",    status: "Confirmed", value: 42800 },
      { name: "Soundtrip",      role: "AV + DJ",     status: "Confirmed", value: 9800 },
      { name: "Mei Photography",role: "Photo+video", status: "Confirmed", value: 7400 },
      { name: "Coach Co.",      role: "Transport",   status: "Pending",   value: 2200 },
      { name: "Sweet Bake Co.", role: "Cake",        status: "Confirmed", value: 1900 },
      { name: "Beach Pavilion", role: "Venue",       status: "Confirmed", value: 22000 },
    ],
    activity: [
      { who: "Maya", what: "moved stage from Negotiation → Won", when: "12 Mar · 09:14" },
      { who: "Jules",what: "uploaded final floor plan (v3) to Files", when: "21 Apr · 11:02" },
      { who: "Maya", what: "added internal note: \"Aunt Vivian must be present at cake cut\"", when: "4 May · 14:48" },
      { who: "Sophie Hartley", what: "WhatsApp: \"Can we move first dance after cake cut?\"", when: "9 May · 21:33" },
      { who: "Maya", what: "WhatsApp reply: \"Confirmed — updated run sheet.\"", when: "9 May · 21:41" },
      { who: "Ravi", what: "issued work order to Coach Co. (2 × 30-seat)", when: "16 May · 10:20" },
    ],
    comms: [
      { kind: "wa",   who: "Sophie Hartley", role: "Bride",  hue: 330,
        time: "9 May · 21:33", text: "Hey Maya — can we move the first dance to AFTER the cake cut? Mum keeps reminding us 🙃" },
      { kind: "wa",   who: "Maya Chen",      role: "Coord.", hue: 252, mine: true,
        time: "9 May · 21:41", text: "Confirmed. Updated the run sheet — cake cut at 21:15, dance immediately after. I'll re-share with the DJ." },
      { kind: "note", who: "Maya Chen",      role: "Internal note", hue: 36,
        time: "4 May · 14:48", text: "Aunt Vivian must be present at the cake cut — couple was firm on this. AV cued to wait for her arrival from terrace." },
      { kind: "email", who: "Pearl Catering", role: "Supplier", hue: 190,
        time: "2 May · 09:12", text: "Final headcount locked at 142, including 4 vegan and 6 gluten-free. Service starts 18:30 sharp." },
    ],
    files: [
      { name: "Hartley · Floor plan v3.pdf",   size: "1.2 MB", date: "21 Apr" },
      { name: "Run sheet · final.pdf",          size: "284 KB", date: "12 May" },
      { name: "Pearl menu · signed.pdf",        size: "612 KB", date: "1 May" },
      { name: "Beach Pavilion · COI.pdf",       size: "98 KB",  date: "14 Apr" },
      { name: "Photo brief · Mei.pdf",          size: "470 KB", date: "28 Apr" },
    ],
    checklist: [
      { group: "Venue",      items: [{ t: "Insurance certificate on file", done: true }, { t: "Site walk-through complete", done: true }, { t: "Wet-weather plan signed off", done: true }] },
      { group: "Catering",   items: [{ t: "Final headcount confirmed", done: true }, { t: "Dietaries collected", done: true }, { t: "Beverage package signed", done: true }] },
      { group: "Florals",    items: [{ t: "Arbor design approved", done: true }, { t: "Table arrangements approved", done: true }, { t: "Bouquet count confirmed", done: false }] },
      { group: "AV",         items: [{ t: "Speech mic check", done: true }, { t: "First dance cue prepared", done: false }] },
      { group: "Day-of",     items: [{ t: "Aunt Vivian arrival noted", done: true }, { t: "Driver list + plate numbers", done: true }, { t: "Carriages confirmed", done: false }] },
    ],
  },

  // Event-day "today" view
  today: {
    eventTitle: "Hartley Wedding · TODAY",
    tiles: [
      { label: "Venue ready",     value: "Yes",       sub: "Walk-through 13:30", state: "ok"   },
      { label: "Suppliers in",    value: "6 / 7",     sub: "Coach Co. arriving 22:30", state: "warn" },
      { label: "Headcount",       value: 142,         sub: "On menu since 02 May", state: "ok"   },
      { label: "Outstanding",     value: 2,           sub: "Bouquets · first-dance cue", state: "warn" },
      { label: "Weather",         value: "16°C / Clear", sub: "Wind 12km/h E · Plan A", state: "ok"   },
      { label: "Cash collected",  value: "$168,000",  sub: "Balance settled 7 Jun", state: "ok"   },
      { label: "Run-sheet flag",  value: "Aunt Vivian", sub: "Required at cake cut 21:15", state: "warn" },
      { label: "Incidents",       value: 0,           sub: "Last 72h", state: "ok"   },
    ],
  },

  audit: [
    { who: "Maya Chen",  act: "event.stage_changed", sum: "Hartley Wedding · Negotiation → Won",         when: "12 Mar 09:14" },
    { who: "Jules Park", act: "file.uploaded",       sum: "Hartley · Floor plan v3.pdf",                  when: "21 Apr 11:02" },
    { who: "Maya Chen",  act: "comm.created",        sum: "Internal note added to Hartley Wedding",        when: "04 May 14:48" },
    { who: "Maya Chen",  act: "comm.created",        sum: "WhatsApp inbound from Sophie Hartley",          when: "09 May 21:33" },
    { who: "Maya Chen",  act: "run_sheet.updated",   sum: "Cake cut moved before first dance",             when: "09 May 21:41" },
    { who: "Ravi Singh", act: "work_order.created",  sum: "Coach Co. — 2 × 30-seat coaches",              when: "16 May 10:20" },
    { who: "Ravi Singh", act: "work_order.status_changed", sum: "Soundtrip · pending → confirmed",         when: "18 May 16:08" },
    { who: "Maya Chen",  act: "quote.created",       sum: "Atlas Capital · EOFY · v2 sent",                when: "22 May 14:30" },
    { who: "system",     act: "lead.created",        sum: "Inbound: Olivia Bennett (Website)",             when: "23 May 09:51" },
  ],
};
